name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Generate
        run: |
          go get golang.org/x/tools/cmd/goimports
          go generate

      - name: Count
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Commit & Push
        run: |
          git config --local user.name ${{secrets.NAME}}
          git config --local user.email ${{secrets.EMAIL}}
          git add .
          git commit -m "Generate"
          git pull
          git push origin master
        if: steps.changes.outputs.count > 0
